<a href="https://colab.research.google.com/github/LivingPythonIA/LivingPythonIA.github.io/blob/main/condiciones_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importar librería

In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [4]:
 arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [3]:
#Validación elemento a elemento
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [6]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [7]:
# Seleccion de elementos basados en alguna condición
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [8]:
#Usando condiciones más complejas
arr[(arr > 5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [9]:
arr[arr > 5] = 99

In [11]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [10]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)