<a href="https://colab.research.google.com/github/LivingPythonIA/LivingPythonIA.github.io/blob/main/copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importar librería

In [1]:
import numpy as np

In [2]:
# Recuperar el arreglo anterior
arr = np.arange(0,11)

# Resultado
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [3]:
# Troceado de arreglos
trozo_de_arr = arr[0:6]

In [5]:
# Cambios
trozo_de_arr[:] = 0

# Mostrar slice nuevamete
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [6]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [7]:
# Para obtener una copia es necesario usar el método copy()
arr_copy = arr.copy()

In [8]:
arr_copy[:] = 100

In [9]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [10]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])