<a href="https://colab.research.google.com/github/LivingPythonIA/LivingPythonIA.github.io/blob/main/creando_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importando librerías

In [1]:
import numpy as np

### Arange

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Zeros

In [4]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Ones

In [5]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Linspace

In [6]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### Eye

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

In [8]:
np.random.rand()

0.46782182652413173

In [9]:
np.random.rand(4)

array([0.62207437, 0.44952282, 0.16021173, 0.50959655])

In [10]:
np.random.rand(4,4)

array([[0.1430139 , 0.87388676, 0.15948669, 0.12613582],
       [0.4305822 , 0.68747154, 0.38979601, 0.41302464],
       [0.91130057, 0.22326136, 0.77023011, 0.58336907],
       [0.64286441, 0.88767705, 0.07350669, 0.16427896]])

In [11]:
np.random.randint(1,15)

9

In [12]:
np.random.randint(1,100,(10,10))

array([[57, 84, 30, 27, 65, 66, 77, 51, 22, 60],
       [95,  5, 81, 67, 18, 13, 36, 28, 80, 94],
       [75, 58, 65, 47,  9, 72, 44, 59, 25, 33],
       [54, 95, 55, 51, 61,  7, 56, 81, 44, 54],
       [27, 83, 46, 35, 12, 75, 37, 57, 61, 94],
       [86, 64, 57, 40, 38, 83,  8, 86, 34, 17],
       [13, 40, 23,  7, 68, 50, 83, 62, 76, 46],
       [20, 17, 76, 85, 29, 76, 23, 48, 61, 78],
       [61, 31, 58, 23, 58, 76, 39, 80, 63, 52],
       [44,  5, 70, 52, 46, 36, 86, 18, 90,  7]])