<a href="https://colab.research.google.com/github/LivingPythonIA/LivingPythonIA.github.io/blob/main/el_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importando librerias

In [1]:
import numpy as np

### Creando listas

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

### Creando array

In [3]:
arr = np.array(lista)

In [4]:
type(arr)

numpy.ndarray

In [5]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Indexing

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[1]

2

In [8]:
arr[0] + arr[5]

7

In [9]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
matriz[0,2]

3

### Slicing

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [13]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr[::3]

array([1, 4, 7])

In [20]:
arr[-1]

9

In [15]:
arr[-3:]

array([7, 8, 9])

In [16]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
matriz[1:,0]

array([4, 7])