<a href="https://colab.research.google.com/github/LivingPythonIA/LivingPythonIA.github.io/blob/main/funciones_principales_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importando librerías

In [1]:
import numpy as np

In [6]:
np.random.randint(1,20,10)

array([ 2, 12, 13, 16, 15, 18, 12, 16, 17, 18])

In [2]:
arr = np.random.randint(1,20,10)

In [7]:
matriz = arr.reshape(2,5)
matriz

array([[15,  7, 14,  8,  8],
       [ 8, 17,  9, 10, 12]])

In [8]:
arr

array([15,  7, 14,  8,  8,  8, 17,  9, 10, 12])

### Max

In [9]:
arr.max()

17

In [10]:
matriz

array([[15,  7, 14,  8,  8],
       [ 8, 17,  9, 10, 12]])

In [12]:
matriz.max()

17

In [17]:
#por filas 1
matriz.max(1)

array([15, 17])

In [18]:
#por columnas 0
matriz.max(0)

array([15, 17, 14, 10, 12])

### Argmax

In [19]:
arr.argmax()

6

In [20]:
matriz.argmax(0)

array([0, 1, 0, 1, 1])

### Min

In [21]:
arr.min()

7

In [22]:
matriz.min(0)

array([8, 7, 9, 8, 8])

### Argmin

In [23]:
arr.argmin()

1

In [25]:
matriz.argmin(0)

array([1, 0, 1, 0, 0])

In [24]:
matriz.argmin(1)

array([1, 0])

### Ptp

In [26]:
arr

array([15,  7, 14,  8,  8,  8, 17,  9, 10, 12])

In [27]:
arr.ptp()

10

In [28]:
matriz.ptp(0)

array([ 7, 10,  5,  2,  4])

### Sort

In [29]:
#ordena de menor a mayor
arr.sort()
arr

array([ 7,  8,  8,  8,  9, 10, 12, 14, 15, 17])

### Percentile

In [31]:
#el mas bajo
np.percentile(arr,0)

7.0

In [30]:
#la mediana
np.percentile(arr,50)

9.5

In [32]:
#el mas alto
np.percentile(arr,100)

17.0

### Median

In [33]:
np.median(arr)

9.5

In [34]:
np.median(matriz,1)

array([ 8., 14.])

### Standard Deviation (std)

In [36]:
np.std(arr)

3.3105890714493698

In [35]:
#igual a la varianza
np.std(arr) ** 2

10.96

### Variance (Var)

In [37]:
np.var(arr)

10.959999999999999

### Mean o media (suma de todos y dividido por el número de elementos)

In [43]:
np.mean(arr)

10.8

### Concatenate

In [45]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [46]:
b = np.array([5,6])
b

array([5, 6])

In [47]:
np.concatenate((a,b),axis=0)

ValueError: ignored

In [49]:
a.ndim

2

In [50]:
b.ndim

1

In [51]:
#ampliamos la dimension
b = np.expand_dims(b,axis=0)

In [52]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
b

array([[5, 6]])

In [54]:
np.concatenate((a,b),axis=1)

ValueError: ignored

In [55]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

### Transpuesta

In [ ]:
b.T

array([[5],
       [6]])