<a href="https://colab.research.google.com/github/LivingPythonIA/LivingPythonIA.github.io/blob/main/operaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importar librerías

In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

In [3]:
lista * 2

[1, 2, 1, 2]

In [6]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr2 = arr.copy()

### Operaciones (aritmética simple al array)

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
1 / arr

<ipython-input-11-6d68a1c1e09c>:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [12]:
#al cuadrado
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### Operaciones entre arrays

In [13]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
arr - arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [17]:
matriz = arr.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
matriz2 = matriz.copy()

In [19]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [21]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [23]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [24]:
#es lo mismo que lo de arriba
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

In [28]:
arr = np.array ([11,11,12,13,13,14,14,12,15])
arr

array([11, 11, 12, 13, 13, 14, 14, 12, 15])

In [29]:
unique = np.unique(arr)
unique

array([11, 12, 13, 14, 15])

In [32]:
unique, ocurrence = np.unique(arr, return_counts=True)
print(unique)

ocurrence

[11 12 13 14 15]


array([2, 2, 2, 2, 1])

In [31]:
np.sort(unique)

array([11, 12, 13, 14, 15])