<a href="https://colab.research.google.com/github/LivingPythonIA/LivingPythonIA.github.io/blob/main/shape_y_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importar librerías

In [1]:
import numpy as np

In [5]:
 np.random.randint(1,10,(3,2))

array([[4, 8],
       [8, 7],
       [5, 7]])

In [2]:
arr = np.random.randint(1,10,(3,2))

### Shape

In [6]:
arr.shape

(3, 2)

In [4]:
arr

array([[2, 4],
       [8, 4],
       [2, 3]])

### Reshape

In [7]:
arr.reshape(1,6)

array([[2, 4, 8, 4, 2, 3]])

In [8]:
arr.reshape(2,3)

array([[2, 4, 8],
       [4, 2, 3]])

In [12]:
np.reshape(arr,(1,6))
arr.reshape(1,6)

array([[2, 4, 8, 4, 2, 3]])

In [10]:
arr

array([[2, 4],
       [8, 4],
       [2, 3]])

In [11]:
np.reshape(arr,(2,3),'C')

array([[2, 4, 8],
       [4, 2, 3]])

In [13]:
np.reshape(arr,(2,3),'F')

array([[2, 2, 4],
       [8, 4, 3]])

In [14]:
np.reshape(arr,(2,3),'A')

array([[2, 4, 8],
       [4, 2, 3]])