<a href="https://colab.research.google.com/github/LivingPythonIA/LivingPythonIA.github.io/blob/main/tipos_de_dato_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importando librerias

In [1]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [2]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [3]:
arr

array([1., 2., 3., 4.])

### Cambiando tipo de datos

In [5]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.float64)
arr

array([0., 1., 2., 3., 4.])

In [4]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [6]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [8]:
arr = np.array(['1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([1, 2, 3, 4], dtype=int8)

In [7]:
arr = np.array(['hola','1','2','3','4'])
arr = arr.astype(np.int8)
arr

ValueError: ignored